# Generated by Django 4.1.9 on 2024-05-08 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Author', '0001_initial'),
        ('Categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('Author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Author.author')),
                ('categories', models.ManyToManyField(to='Categories.categories')),
            ],
        ),
    ]
